version: '3'
services:
  db:
    image: postgres
    # volumes:
    #   - psgl_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
volumes:
  psgl_data: